feat: File backed variable values
cloudquery/docs pull request #111
Opened 2022-03-08 17:57 UTC by disq

2022-03-08 18:02 UTC, bbernays commented on docs/configuration/environment-variable-substitution.md
> +        }
Does it work if you have multiple accounts?

```suggestion
        accounts "012345678910" {
          role_arn = "${ARN_012345678910}"
        }
        accounts "012345678911" {
          role_arn = "${ARN_012345678911}"
        }

```

2022-03-08 18:12 UTC, bbernays commented on docs/configuration/environment-variable-substitution.md
> +      }
Could a customer combine env variables together?

```suggestion
      connection {
        dsn = "postgres://${USERNAME}:${PASSWORD}@${HOST}:${PORT}/${DBNAME}?sslmode=${SSLMODE}"
      }
```

2022-03-08 18:22 UTC, disq commented on docs/configuration/environment-variable-substitution.md
> +        }
I hope so :)

2022-03-08 18:22 UTC, disq commented on docs/configuration/environment-variable-substitution.md
> +      }
Yes I think

2022-03-09 15:01 UTC, bbernays approved these changes
LGTM

2022-03-09 15:05 UTC, ukmadlz requested changes

2022-03-09 15:05 UTC, ukmadlz commented on docs/configuration/file-backed-variable-values.md
> +            dsn = file("dsn.txt")
Just a little indentation fix

2022-03-09 15:09 UTC, disq commented on docs/configuration/file-backed-variable-values.md
> +            dsn = file("dsn.txt")
indented

2022-03-09 15:19 UTC, ukmadlz approved these changes

2022-03-09 15:26 UTC, merged