Add schema docs
cloudquery/docs pull request #268
Opened 2022-07-12 21:47 UTC by bbernays

2022-07-12 21:49 UTC, disq reviewed
Would also add it in the yaml block above

2022-07-13 09:01 UTC, shimonp21 commented on docs/configuration/overview.md
> +* **`schema`** **(optional)** - The name of the schema that CloudQuery will use for reads and writes unless otherwise defined. Default value is `public`
"unless otherwise defined" seems unnecessary. I would even remove "for reads and writes".

Maybe just "The name of the schema that CloudQuery will use. Default value is `public`". 

Also, let's add the caveat about the schema needing to exist beforehand: "Note that the schema must already exist before executing `fetch`."

2022-07-13 09:02 UTC, shimonp21 requested changes
Thanks! PTAL at my comment :)

2022-07-13 11:45 UTC, bbernays commented on docs/configuration/overview.md
> +* **`schema`** **(optional)** - The name of the schema that CloudQuery will use for reads and writes unless otherwise defined. Default value is `public`
We can't claim everything occurs in that schema because we do still write to the `cloudquery` schema.

2022-07-13 12:57 UTC, merged