WIP: some restructuring
cloudquery/docs pull request #37
Opened 2021-11-13 10:56 UTC by yevgenypats

Do not review yet: This is still WIP.

Mainly trying to put the same structure for each command we have:

```
--> CLI
    ---> command
        --> Overview
        --> Configuration
```

Also updating key features & use-cases as they were pretty old and not cristal clear.

2021-11-13 11:02 UTC, disq commented on docs/cli/drift/configuration.md
> +    terraform {
This is wrong. `terraform {` is its own block and it defines where to access tfstate files.

2021-11-13 11:03 UTC, disq commented on docs/cli/drift/overview.md
> +**Infrastructure Drift** - When what is defined in your IaC is different from what is provisioned in your Cloud. This is a very command scenario and can happen due human error, manual changes and var
suggestion: Prepend with `> ` ("quoted") so it's shown in a box

2021-11-13 13:27 UTC, yevgenypats commented on docs/cli/drift/configuration.md
> +    terraform {
I basically just move this file https://github.com/cloudquery/docs/pull/36/files#diff-d74864886c0044889d03d46f938f63f150461311265acf909b262755ed547475R16 to `cli/drift/configuration`.

is it incorrect their as well ?

2021-11-13 13:28 UTC, yevgenypats commented on docs/cli/drift/configuration.md
> +    terraform {
Ah sorry, I see it was updated. I'll rebase.

2021-11-13 13:41 UTC, yevgenypats commented on docs/cli/drift/overview.md
> +**Infrastructure Drift** - When what is defined in your IaC is different from what is provisioned in your Cloud. This is a very command scenario and can happen due human error, manual changes and var
Done.

2021-11-13 13:43 UTC, yevgenypats commented
Ready for review.

There is still more work to do in various areas of the documentation but I think it's best to do that in steps and different PRs (https://github.com/cloudquery/docs/issues/38 and some other places where we have a bit outdated documentation).

2021-11-13 16:47 UTC, disq requested changes

2021-11-13 16:47 UTC, disq commented on docs/cli/fetch/configuration.md
> +This section is very similar to terraform providers section due to similar design of CloudQuery providers, but their purpose and implementation is completly different:
```suggestion
This section is very similar to terraform providers section due to similar design of CloudQuery providers, but their purpose and implementation is completely different:
```

2021-11-13 16:47 UTC, disq commented on docs/cli/fetch/configuration.md
> +CloudQuery providers are read only providers which extracts,transform and loads cloud assets configuration while Terraform providiers interacts with the cloud to provision assets.
```suggestion
CloudQuery providers are read only providers which extracts, transforms and loads cloud assets configuration while Terraform providers interact with the cloud to provision assets.
```

2021-11-14 13:46 UTC, roneli approved these changes
LGTM

2021-11-15 09:02 UTC, merged