improve providers documentation
cloudquery/docs pull request #41
Opened 2021-11-17 20:10 UTC by yevgenypats

2021-11-17 20:30 UTC, disq requested changes

2021-11-17 20:30 UTC, disq commented on docs/cli/configuration/overview.md
>  This is an overview for the syntax and configuraiton options of CloudQuery main configuraiton file `config.hcl`.
configuraiton

2021-11-17 20:30 UTC, disq commented on docs/cli/configuration/providers.md
> +> If you are familiar with terraform we use the [same pluggable architecture](https://www.terraform.io/docs/language/providers/index.html) just instead of provisioning infrastructure we focus on extr
add full stop on end of line?

2021-11-17 20:30 UTC, disq commented on docs/cli/configuration/providers.md
> +- **official** - Owned and Maintained by CloudQuery team
```suggestion
- **official** - Owned and maintained by CloudQuery team
```

2021-11-17 20:30 UTC, disq commented on docs/cli/configuration/providers.md
> +- **community** - Owned and maintined by either individuals or third-party vendors.
```suggestion
- **community** - Owned and maintained by either individuals or third-party vendors.
```

2021-11-17 21:48 UTC, yevgenypats commented on docs/cli/configuration/overview.md
>  This is an overview for the syntax and configuraiton options of CloudQuery main configuraiton file `config.hcl`.
I changed it to a whole category(directory) so this file is now an `overview` of our configuration ?

2021-11-17 21:51 UTC, disq commented on docs/cli/configuration/overview.md
>  This is an overview for the syntax and configuraiton options of CloudQuery main configuraiton file `config.hcl`.
line 3, typo, configuration

2021-11-17 22:00 UTC, yevgenypats commented on docs/cli/configuration/overview.md
>  This is an overview for the syntax and configuraiton options of CloudQuery main configuraiton file `config.hcl`.
thx. fixed.

2021-11-17 22:00 UTC, yevgenypats commented on docs/cli/configuration/providers.md
> +> If you are familiar with terraform we use the [same pluggable architecture](https://www.terraform.io/docs/language/providers/index.html) just instead of provisioning infrastructure we focus on extr
done.

2021-11-18 08:25 UTC, disq requested changes
one last nit

2021-11-18 08:25 UTC, disq commented on docs/cli/configuration/providers.md
> +> If you are familiar with terraform we use the [same pluggable architecture](https://www.terraform.io/docs/language/providers/index.html). CloudQuery providers focus on extracting & transforming con
```suggestion
> If you are familiar with Terraform we use the [same pluggable architecture](https://www.terraform.io/docs/language/providers/index.html). CloudQuery providers focus on extracting & transforming configuration from infrastructure, instead of provisioning it.
```

Not sure about the comma, could be written better I suppose

2021-11-18 09:20 UTC, roneli approved these changes
LGTM

2021-11-18 10:06 UTC, merged