initial history docs commit
cloudquery/docs pull request #54
Opened 2021-12-02 10:02 UTC by roneli

2021-12-03 01:10 UTC, yevgenypats requested changes
few comments

2021-12-03 01:10 UTC, yevgenypats commented on docs/history.md
> +  history {
When we do `cloudquery init` do we have defaults? I suggest to output those defaults as well and if it's not a timescaledb just to ignore them and print an info/warn

2021-12-03 01:10 UTC, yevgenypats commented on docs/history.md
> +SELECT * from aws_iam_users
I'll add another example with date

2021-12-03 01:10 UTC, yevgenypats commented on sidebars.js
> +      type: 'doc',
I think at the current structure it should be under `cli/fetch`

2021-12-05 20:16 UTC, roneli commented on docs/history.md
> +  history {
only if this block is defined, history is enabled.

2021-12-05 20:57 UTC, closed without merging