SDK docs: initial commit
cloudquery/docs pull request #69
Opened 2021-12-21 14:32 UTC by disq

2021-12-22 10:13 UTC, ukmadlz commented on docs/developers/sdk/overview.md
> +CloudQuery SDK enables building CloudQuery providers which allows CloudQuery's users to extract/load/transform existing and popular service providers as well as custom in-house solutions into a SQL o
Do we still enable loading into a graph?

2021-12-22 10:13 UTC, ukmadlz commented on docs/developers/sdk/overview.md
> +- **Resolvers** define how to fetch resources from the source (the cloud provider). [Utility resolvers](https://github.com/cloudquery/cq-provider-sdk/blob/main/provider/schema/resolvers.go) take this
Should we expand in these docs or are we relying on the comments for each util function?

2021-12-22 13:26 UTC, disq commented on docs/developers/sdk/overview.md
> +- **Resolvers** define how to fetch resources from the source (the cloud provider). [Utility resolvers](https://github.com/cloudquery/cq-provider-sdk/blob/main/provider/schema/resolvers.go) take this
It will be expanded.

2021-12-22 16:59 UTC, roneli requested changes
Added some comments.

2021-12-22 16:59 UTC, roneli commented on docs/developers/sdk/overview.md
> +CloudQuery SDK enables building CloudQuery providers which allows CloudQuery's users to extract/load/transform existing and popular service providers as well as custom in-house solutions into a SQL o
No it should be removed for now, in future versions we might support a graph DB.

2021-12-22 16:59 UTC, roneli commented on docs/developers/sdk/overview.md
> +CloudQuery SDK enables building CloudQuery providers which allows CloudQuery's users to extract/load/transform existing and popular service providers as well as custom in-house solutions into a SQL o
nit: I suggest to make E L T in the extract transform load bold

2021-12-22 16:59 UTC, roneli commented on docs/developers/sdk/overview.md
> +- **Provider** structs are the main core of the SDK that requires the implementor to create it list all available resources, configuration of it's client and it's config. The provider structs impleme
```suggestion
- **Provider** structs are the core component of the SDK that require the implementor to only set a list all available resources, configuration of it's client and it's config. The provider structs implements the CQProvider Interface allowing the user to just implement his resources and configure function.
```

2021-12-22 16:59 UTC, roneli commented on docs/developers/sdk/overview.md
> +- **Resolvers** are functions to fetch resources from the source (the cloud provider). [Utility resolvers](https://github.com/cloudquery/cq-provider-sdk/blob/main/provider/schema/resolvers.go) take t
I think we might want to distinct between TableResolver and ColumnResolver and PostResourceResolver?

2021-12-22 16:59 UTC, roneli commented on docs/developers/sdk/provider/overview.md
> +Provider structs are the main core of the SDK that requires the implementor to create it list all available resources, configuration of it's client and it's config. The provider structs implements th
duplicated from the bullets in the main overview, we might need to restructure it + maybe we can deep dive more on each field here in the structure.

2021-12-22 17:07 UTC, disq commented on docs/developers/sdk/provider/overview.md
> +Provider structs are the main core of the SDK that requires the implementor to create it list all available resources, configuration of it's client and it's config. The provider structs implements th
yeah I didn't say it wasn't duplicated... 🥲

2021-12-22 17:32 UTC, disq commented on docs/developers/sdk/overview.md
> +- **Resolvers** are functions to fetch resources from the source (the cloud provider). [Utility resolvers](https://github.com/cloudquery/cq-provider-sdk/blob/main/provider/schema/resolvers.go) take t
Done

2021-12-24 06:59 UTC, roneli requested changes
Looks good, had a few comments, and some missing info, but overall looks great! lets get this shipped today :)

2021-12-24 06:59 UTC, roneli commented on docs/developers/sdk/provider/error-classifier.md
> +
maybe it is important to add that any errors returned during the execution that already satisfy the diagnostic interface will not be required to be classified again.

2021-12-24 06:59 UTC, roneli commented on docs/developers/sdk/table/fetch-resolvers.md
> +Fetch resolvers are functions to fetch resources from the source (the cloud provider).
maybe bad wording, but it can be any source not only cloud providers (github/another SaaS etc')
```suggestion
Fetch resolvers are functions to fetch resources from the source (a cloud provider for example).
```

2021-12-24 06:59 UTC, roneli commented on docs/developers/sdk/table/fetch-resolvers.md
> +The thing to do in a `TableResolver` is to access the cloud resource using the given `*Client` and query all resources of that type. Then push every item into the given `chan`.
```suggestion
`TableResolver` allows you to access the cloud resource using the given passed `*Client` and fetch all resources of that type. Finally, you send the fetch items into the passed `res` channel argument.
The `TableResolver` is very flexible allowing you to define you pagination logic or any other logic for that matter, and pass the results to channel.
```

2021-12-24 06:59 UTC, roneli commented on docs/developers/sdk/table/fetch-resolvers.md
> +```go
maybe add an example of post resource resolver? s3 is a good one for example or mq/sns has a nice one as well.

2021-12-24 06:59 UTC, roneli commented on docs/developers/sdk/table/multiplexer-and-deletefilter.md
> +A multiplexer get a client and returns a bunch of clients:
```suggestion
A multiplexer receives a client and returns an array of clients to execute in parallel:
```

2021-12-24 06:59 UTC, roneli commented on docs/developers/sdk/table/primary-key.md
> +Every table should have a primary key, ideally consisting of the `account_id` and `id` (or `arn`) of some kind. If the provider supports multiple service regions (and multiple entities with the same
Only Root tables should have PKS ideally also relations, but its harder since sometimes not all relations have PKs.

Ill mention this in this comment as well, we should talk about cq_id and parent_cq_id resolvers that should be added to relations, moreover if a user doesn't define any PK the cq_id is always added.

Adding into this I would probably also mention in table that we add the following columns meta, cq_fetch_date, cq_id to each table, and are reserved. In hindsight meta -> cq_meta. 

```suggestion
Every `root`  table should have a primary key, ideally consisting of the `account_id` and `id` (or `arn`) of some kind. If the provider supports multiple service regions (and multiple entities with the same `id` can exist in different regions) `region` column should also be included.
```

2021-12-24 06:59 UTC, roneli commented on docs/developers/sdk/table/overview.md
> +Here we define a table with its columns and metadata.
```suggestion
##### Here we define a table with its columns and metadata.
```
maybe this would be nicer as a block footer? not sure, just a trial

2021-12-24 06:59 UTC, roneli commented on docs/developers/sdk/provider/overview.md
> +Check [the repository](https://github.com/cloudquery/cq-provider-sdk/blob/main/provider/provider.go) for the `Provider` definition.
maybe link from here to the provider section in docs for how to configure the provider and add there for full Provider definition details go to the repository?

2021-12-24 16:22 UTC, disq commented on docs/developers/sdk/provider/error-classifier.md
> +
so, errorclassifier is not called if the err is already diag.Diagnostic?

2021-12-24 16:42 UTC, disq commented on docs/developers/sdk/provider/overview.md
> +Check [the repository](https://github.com/cloudquery/cq-provider-sdk/blob/main/provider/provider.go) for the `Provider` definition.
it's already literally linked ("Next" link)

2021-12-24 16:45 UTC, disq commented on docs/developers/sdk/table/overview.md
> +Here we define a table with its columns and metadata.
It becomes bold.

2021-12-24 16:56 UTC, disq commented on docs/developers/sdk/table/primary-key.md
> +Every table should have a primary key, ideally consisting of the `account_id` and `id` (or `arn`) of some kind. If the provider supports multiple service regions (and multiple entities with the same
Added

2021-12-24 16:57 UTC, disq commented on docs/developers/sdk/table/fetch-resolvers.md
> +```go
Done

2021-12-24 17:24 UTC, roneli commented on docs/developers/sdk/table/overview.md
> +Here we define a table with its columns and metadata.
so no need

2021-12-24 17:25 UTC, roneli commented on docs/developers/sdk/provider/error-classifier.md
> +
https://github.com/cloudquery/cq-provider-sdk/blob/f461b2e2b79d9052711a8b41e9b6d21f9af19498/provider/provider.go#L249 it should yes, sometimes wrapping can ruin it but it should not be called in that case.

2021-12-24 17:29 UTC, roneli approved these changes
LGTM

2021-12-24 18:02 UTC, merged