add testing sdk docs
cloudquery/docs pull request #70
Opened 2021-12-26 15:24 UTC by yevgenypats

2022-01-04 08:43 UTC, roneli requested changes
Looks good, added some comments, you are missing a mention to the IgnoreInTests flag

2022-01-04 08:43 UTC, roneli commented on docs/developers/sdk/overview.md
> +It was developed to allow easy creation for providers and reduce boilerplate code when developing them, letting developers focus only on the **E**xtract while the SDK will take care of the rest.
```suggestion
It was developed to allow easy creation for providers and reduce boilerplate code when developing them, giving developers solely on the **E**xtract while the SDK takes care of the rest. 
```

2022-01-04 08:43 UTC, roneli commented on docs/developers/sdk/overview.md
> +The core idea of the SDK is to allow for developers developing a provider in a straightforward manner, while allowing the user free control in fetching the data to be inserted.
```suggestion
The core idea of the SDK is to allow developing a provider in a straightforward manner, while allowing the user free control in fetching the data to be inserted.
```

feels redundant

2022-01-04 08:43 UTC, roneli commented on docs/developers/sdk/testing.md
> +Testing your provider is key in ensuring quality of your provider and developer experiance for future contributors that can easily test their changes against the tests.
```suggestion
Testing providers is key factor in ensuring the quality of your provider and developer experience, so future contributors can easily test their changes against.
```

2022-01-04 08:43 UTC, roneli commented on docs/developers/sdk/testing.md
> +CloudQuery SDK provides utility test function to help test each resource and verify it's output.
```suggestion
CloudQuery SDK provides an utility test function to help you test each resource and verify it's output.
```

2022-01-04 08:43 UTC, roneli commented on docs/developers/sdk/testing.md
> +The testing framework provided by CloudQuery SDK is essentially an end-to-end (integration) tests. This means you will need a real test account and real resources in place. It is suggested to create
```suggestion
The testing framework provided by CloudQuery SDK are essentially an end-to-end (integration) tests. This means you will need a real test account and real resources in place. It is suggested to create those test resources with any IaC tool (Terraform, Pulumi, etc...).
```
either `are ... e2e tests` or is ... e2e test`

2022-01-04 08:43 UTC, roneli commented on docs/developers/sdk/testing.md
> +Here is the flow of each test:
Maybe  subtitle it?

```suggestion
### Test flow execution:
```

2022-01-04 10:43 UTC, yevgenypats commented on docs/developers/sdk/testing.md
> +CloudQuery SDK provides utility test function to help test each resource and verify it's output.
an utility ? a utility maybe ?

2022-01-04 10:53 UTC, yevgenypats commented
@roneli I mentioned the IgnoreInTest flag for column and rows. I don't mention it for `TestResource` because it's just temporary. it will only be available in the table and column as otherwise we will have to duplicate structs and have long nested structs in `TestResource` for resources with nested children.

2022-01-05 18:30 UTC, disq requested changes

2022-01-05 18:30 UTC, disq commented on docs/developers/sdk/overview.md
> +**The CloudQuery SDK** enables building CloudQuery providers which allows CloudQuery's users to **E**xtract/**T**ransform/**L**oad existing and popular service providers APIs as well as custom in-hou
```suggestion
**The CloudQuery SDK** enables building CloudQuery providers which allows CloudQuery's users to **E**xtract/**T**ransform/**L**oad existing and popular service provider APIs as well as custom in-house solutions into a SQL database.
```

2022-01-05 18:30 UTC, disq commented on docs/developers/sdk/overview.md
> +It was developed to allow easy creation for providers and reduce boilerplate code when developing them, giving developers to solely focus on the **E**xtract while the SDK takes care of the rest.
```suggestion
It was developed to allow easy creation for providers and reduce boilerplate code when developing them, enabling developers to solely focus on the **E**xtract while the SDK takes care of the rest. 
```

2022-01-05 18:30 UTC, disq commented on docs/developers/sdk/testing.md
> +Testing providers is key factor in ensuring the quality of your provider and developer experience, so future contributors can easily test their changes against.
against... ? Smells like an incomplete sentence, I think

2022-01-05 18:30 UTC, disq commented on docs/developers/sdk/testing.md
> +The testing framework provided by CloudQuery SDK are essentially an end-to-end (integration) tests. This means you will need a real test account and real resources in place. It is suggested to create
```suggestion
The testing framework provided by CloudQuery SDK are essentially end-to-end (integration) tests. This means you will need a real test account and real resources in place. It is suggested to create those test resources with any IaC tool (Terraform, Pulumi, etc...).
```

2022-01-05 18:30 UTC, disq commented on docs/developers/sdk/testing.md
> +- Check the schema definition and all columns resolvers that are defined correctly and the data exists after a successful fetch.
```suggestion
- Check the schema definition and all column resolvers are defined correctly, the data exists after a successful fetch.
```

2022-01-05 18:30 UTC, disq commented on docs/developers/sdk/testing.md
> +- The resource table and all it's children tables are delted from PostgreSQL to work with clean data.
```suggestion
- The resource table and all it's children tables are deleted from PostgreSQL to work with a clean state.
```

2022-01-05 18:30 UTC, disq commented on docs/developers/sdk/testing.md
> +- CloudQuery SDK is fetching the resource, transforming and loading it into PostgreSQL.
```suggestion
- CloudQuery SDK fetches the resource, transforms and loads it into PostgreSQL.
```

2022-01-05 18:30 UTC, disq commented on docs/developers/sdk/testing.md
> +- For each resource table (and it's children) CloudQuery is reading all the rows and checking that
```suggestion
- For each resource table (and it's children) CloudQuery reads all the rows and checks that 
```

2022-01-05 18:30 UTC, disq commented on docs/developers/sdk/testing.md
> +Each resource can be tested end-to-end with `ResourceTest` function. Here is an example
```suggestion
Each resource can be tested end-to-end with `ResourceTest` function. Here is an example:
```

2022-01-09 19:37 UTC, merged