Add 'Getting started with AWS' page
cloudquery/docs pull request #81
Opened 2022-02-01 12:57 UTC by shimonp21

DONT MERGE BEFORE adding 'Getting started with GCP', 'Getting started with Azure', and maybe 'Getting started with other cloud providers.

2022-02-01 13:09 UTC, ukmadlz reviewed
Should this be put under the `/tutorials` directory? Especially as it'll be N of them?

2022-02-01 13:17 UTC, ukmadlz requested changes

2022-02-01 13:17 UTC, ukmadlz commented on docs/getting-started-with-aws.mdx
> +## Download and Install
This section should be a link to `/docs/getting-started` otherwise repetitive for all pages

2022-02-01 13:17 UTC, ukmadlz commented on docs/getting-started-with-aws.mdx
> +```hcl
Reference https://github.com/cloudquery/docs/pull/80 for up-to-date changes

2022-02-01 13:26 UTC, shimonp21 commented on docs/getting-started-with-aws.mdx
> +```hcl
Hmmm, shouldn't be any merge conflict I think, right?

2022-02-01 13:29 UTC, ukmadlz commented on docs/getting-started-with-aws.mdx
> +```hcl
More the `config.hcl` has changes for the `--*-dir` paths

2022-02-01 13:29 UTC, shimonp21 commented on docs/getting-started-with-aws.mdx
> +## Download and Install
I think the rationale is to actually have some repetition between 'Getting Started with AWS', 'Getting Started with Azure', 'Getting Started with GCP' - since the ease of onboarding for the users of big-3 clouds is so important. See the terraform docs for example: https://learn.hashicorp.com/terraform

The general 'Getting Started' page will probably be deleted.

 

@yevgenypats 
@roneli

2022-02-01 13:33 UTC, ukmadlz commented on docs/getting-started-with-aws.mdx
> +## Download and Install
That being the case, should it at least be converted to an include block?

2022-02-01 13:37 UTC, bbernays commented on docs/getting-started-with-aws.mdx
> +- CloudQuery is able to use SSO credentials stored in the ~/.aws/ directory.
Cloudquery respects the AWS credential provider chain. So first it grabs from environment variables, then the credentials file at `~/.aws/` then the instance metadata endpoint for containers and ec2 instance

2022-02-01 14:10 UTC, shimonp21 commented
Thanks for the comments guys - I am moving this discussion to https://github.com/cloudquery/docs/pull/82 [because cloudflare doesn't run on forks]..
I will make sure not to lose any of the comments on this thread either

2022-02-01 14:11 UTC, shimonp21 commented on docs/getting-started-with-aws.mdx
> +```hcl
Sorry, I didn't exactly understand what you mean..

2022-02-02 11:40 UTC, shimonp21 commented on docs/getting-started-with-aws.mdx
> +- CloudQuery is able to use SSO credentials stored in the ~/.aws/ directory.
Thanks for explaining! I tried to add this explanation to the guide - PTAL the latest version at https://github.com/cloudquery/docs/pull/82

2022-02-02 12:04 UTC, shimonp21 commented on docs/getting-started-with-aws.mdx
> +## Download and Install
Great idea! do you have a link for how to implement this in docusaurus?

2022-02-02 12:24 UTC, shimonp21 commented on docs/getting-started-with-aws.mdx
> +## Download and Install
Found it: https://docusaurus.io/docs/markdown-features/react#importing-markdown

2022-02-03 10:03 UTC, closed without merging

2022-02-03 10:03 UTC, shimonp21 commented
Closed in favour of https://github.com/cloudquery/docs/pull/82