docs: Add 'Writing Your Own Policies' tutorial
cloudquery/docs pull request #91
Opened 2022-02-09 10:29 UTC by shimonp21

2022-02-09 12:23 UTC, yevgenypats commented on docs/tutorials/policies/getting-started-with-policies.mdx
> +Running prewritten policies is all well and good, but how to write your own policies and queries?
I'd keep it more professional. Just Writing your own policy.

2022-02-11 14:59 UTC, ukmadlz commented on docs/tutorials/policies/policies-overview.mdx
> +[GCP](https://hub.cloudquery.io/policies/cloudquery/gcp/latest/policies), [Azure](https://hub.cloudquery.io/policies/cloudquery/azure/latest/policies)).
```suggestion
[GCP](https://hub.cloudquery.io/policies/cloudquery/gcp/latest/policies), [Azure](https://hub.cloudquery.io/policies/cloudquery/azure/latest/policies))
```

2022-02-12 20:59 UTC, roneli requested changes
Added some comments.

2022-02-12 20:59 UTC, roneli commented on docs/tutorials/policies/writing-your-first-policy.mdx
> +absoute pats will not work**
```suggestion
absolute paths will not work**
```

2022-02-12 20:59 UTC, roneli commented on docs/tutorials/policies/writing-your-first-policy.mdx
> +- Next, the `check` block describes the "meat" of the policy - which checks to run.
nit: different word for "meat" perhaps.

2022-02-12 20:59 UTC, roneli commented on docs/tutorials/policies/writing-your-first-policy.mdx
> +  - You can have multiple `providers` in this section, if your policy queries several different clouds.
its only mandatory in the root policy.

2022-02-12 20:59 UTC, roneli commented on docs/tutorials/policies/views.mdx
> +You can read more about the log4j vulnerability and the `public_egress` poicy int [this blog post](https://www.cloudquery.io/blog/aws-log4j-and-finding-unrestricted-outbound-access).
you explain the rationale of log4j, but I was expecting the rationale of why we should use views, which is to reduce query complexity, specially if the are multiple checks that would benefit from it.

2022-02-12 20:59 UTC, roneli commented on docs/tutorials/policies/subpolicies.mdx
> +```
this didn't render nicely.

2022-02-14 07:46 UTC, shimonp21 commented on docs/tutorials/policies/writing-your-first-policy.mdx
> +- Next, the `check` block describes the "meat" of the policy - which checks to run.
How About "core"?

2022-02-14 07:57 UTC, shimonp21 commented on docs/tutorials/policies/writing-your-first-policy.mdx
> +- Next, the `check` block describes the "meat" of the policy - which checks to run.
how about "core"?

2022-02-14 07:58 UTC, shimonp21 commented on docs/tutorials/policies/writing-your-first-policy.mdx
> +  - You can have multiple `providers` in this section, if your policy queries several different clouds.
Removed the word "mandatory"

2022-02-14 07:58 UTC, shimonp21 commented on docs/tutorials/policies/views.mdx
> +You can read more about the log4j vulnerability and the `public_egress` poicy int [this blog post](https://www.cloudquery.io/blog/aws-log4j-and-finding-unrestricted-outbound-access).
Agreed - removed most of the explanations, leaving only the link to the blog.
Added another sentence about the benefits of using views.

2022-02-14 07:58 UTC, shimonp21 commented on docs/tutorials/policies/subpolicies.mdx
> +```
Fixed

2022-02-15 08:05 UTC, merged